# Generated by Django 5.2 on 2025-04-29 18:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('query', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('views', models.CharField(blank=True, max_length=20)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('video_id', models.CharField(max_length=20)),
                ('video_title', models.CharField(max_length=255)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Video Histories',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
