# Generated by Django 5.2 on 2025-04-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('entities', models.JSONField()),
                ('skills', models.JSONField()),
                ('missing_skills', models.JSONField()),
                ('word_count', models.IntegerField()),
                ('sentence_count', models.IntegerField()),
                ('experience', models.FloatField()),
                ('education_level', models.CharField(max_length=100)),
                ('grammar_score', models.FloatField()),
                ('keyword_density', models.FloatField()),
                ('overall_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
