# Generated by Django 5.2 on 2025-04-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='grammar_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='keyword_density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
