# Generated by Django 5.2 on 2025-04-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_resumeanalysis_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
